name: accounting_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  flutter_bloc: ^9.0.0
  dio: ^5.7.0
  json_annotation: ^4.9.0
  meta: ^1.15.0
  bloc: ^9.0.0
  intl: ^0.20.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  generate: true
  uses-material-design: true
